### ISSUE TITLE
Release dependency issue

### ISSUE THREAD

**Issue by SaltfishAmi** [mfosse/JoyCon-Driver#1]
The executable file from Release.zip notifies me about missing dependencies like "vcruntime140**d**.dll" and "ucrtbase**d**.dll" which are obviously debug versions. I tried modifying the configurations and recompiled in VS2013, and it worked normally on a computer without VS installed, but I'm not sure if there would be issues when I recompile the 2015 project in VS2013.
Could you fix this? Thanks

**Comment by mfosse** [comment]
I've included vcruntime140.dll and ucrtbase.dll in the release section now, so this should be fixed, let me know if there are any other dll problems.

**Comment by SaltfishAmi** [comment]
It still notifies me about missing VCRUNTIME140**_D_**.dll and ucrtbase**_d_**.dll.

**Comment by mfosse** [comment]
But it's compiled in release mode! D:

**Comment by akatsukle** [comment]
It's been a while since the issue was closed, but I'm running into the same issue.
When I try to run the exe in the git, I'm getting 'missing vcruntime140d.dll'.
