### ISSUE TITLE
Steam Support?

### ISSUE THREAD

**Issue by josh-degraw** [mfosse/JoyCon-Driver#118]
So I got this all set up and working, verified via vjoy Monitor. I've tried setting up the controllers to work in Steam, and I don't know if it's just an issue in steam itself, but It doesn't seem to work well. I'll get through mapping buttons and it'll just shut off. I was _kind of_ able to get it to work with a single Joy-Con, but not really.

Basically my question is, is this supposed to work with steam games? I couldn't see anything in the README about it, and I couldn't find anything in the issues either. If this is the wrong solution for this, then I'll gladly keep looking elsewhere, but if this works that would be awesome.

Thanks for the help!

**Comment by Monkeor** [comment]
More or less the same issue. Best I could get was for steam to recognize half of the button inputs a full second late.

**Comment by josh-degraw** [comment]
@Monkeor yeah I had that exact same problem too.

**Comment by josh-degraw** [comment]
@Monkeor Interesting. I'll have to check that out, thanks!
