### ISSUE TITLE
Setting LEDs... doesn't end

### ISSUE THREAD

**Issue by MaxCej** [mfosse/JoyCon-Driver#12]
It successfully combines both JoyCons but gets stuck setting the LED for the right JoyCon. After running it a few times, it eventually set both LEDs but I still had to manually stop the execution. Hope to be helpful!
![image](https://user-images.githubusercontent.com/3941843/27468354-c0cfcea0-57bf-11e7-824c-2ae4756f4bdd.png)

**Comment by NoThisIsStupider** [comment]
There's just no completion message, did you make sure inputs could be seen in joy.cpl first? I noticed the same thing but it still works.

**Comment by MaxCej** [comment]
Sorry for the delayed response. The driver works perfectly. Just had to configure the offsets a bit. The issue I was referring to is that I have to initialize the Joy-Con driver 2 or 3 times for both joy-con LEDs to set and stop blinking.
