### ISSUE TITLE
Error after aquiring 64 bit versions of ucrtbased and vcruntime140d dlls

### ISSUE THREAD

**Issue by Stevenisnormal** [mfosse/JoyCon-Driver#13]
After putting both Dlls in my win32 build folder, I get the following message when I try to run the program:

"The procedure entry point _CrtDbgReportW could not be located in the dynamic link library"
Then it displays the file path of the hidapi dll.

Do I need a clean copy of this dll? Is it not 64 bit?

**Comment by ttay24** [comment]
Wouldn't win32 be 32 bit? Is it in the right folder?

Might also check with a dependency checker and see if it's those DLLs still?

________________________________

**Comment by Stevenisnormal** [comment]
Okay, I tried a dependency checker with 64 bit and 32 bit DLLs

64 bit:
![64 bit](https://user-images.githubusercontent.com/22274373/27486727-8041daf0-57ff-11e7-87fa-f19272170d9c.PNG)

32 bit:
![32 bit](https://user-images.githubusercontent.com/22274373/27486728-8045bd0a-57ff-11e7-8aee-c39f5b75be0f.PNG)

Thank you for any help I receive!

**Comment by ttay24** [comment]
So it looks like maybe UCRTBASED.dll isn't working so good? Per some guy on the internet, he fixed that dependency by installing the windows SDK: https://stackoverflow.com/a/44334289


_____________________________

**Comment by mfosse** [comment]
Win32 ≠ 64bit
I only compile the program in 32bit mode since there's no need for it to be 64bit and it being 32bit makes it work for 32bit and 64bit windows.

**Comment by mfosse** [comment]
I'm still not sure why any dlls are needed since I link statically but I'll do some research and fix it later today

**Comment by ttay24** [comment]
I would think if it's being built with VS2015 and you're the one compiling it...then it should work.

But if you compile in debug mode, it's going to require that debug version of the runtime

________________________________

**Comment by mfosse** [comment]
Yeah I've updated it to only include the release version, and added the necessary dlls
