### ISSUE TITLE
Gyro Data

### ISSUE THREAD

**Issue by mfosse** [mfosse/JoyCon-Driver#14]
I'm creating this because I'm not sure how I'm going to handle motion controls with vJoy yet, and I might want some feedback. currently it's just roll and pitch in the Rz and sl0 sliders in vJoy.

**Comment by NoThisIsStupider** [comment]
I don't know how feasible this is, but if it were possible to spoof a PS4 controller with all the axis, and have steam detect it as a PS4 controller, all the power of Steam's gyro stuff would be open to the Joycons. A far easier approach would be to replicate some of the more basic parts of the SCAPI, such as gyro on right stick and hold a button to activate gyro. This at the very least would make aiming in games much easier as well as more comfortable. The S buttons would be good for the activate Gyro command.

It would also be nice if the accelorometer data could be used, perhaps through a second vJoy device, for full Wiimote motion control emulation on non-motion-plus games.
