### ISSUE TITLE
Full protocol reverse engineering

### ISSUE THREAD

**Issue by gourryinverse** [mfosse/JoyCon-Driver#16]
We need to get the packets fully reversed, or at least to a point where we can be confident that the sticks and motion control fields are correct.  

Going to try to get some profiling done on un-explored sections of the packets, and maybe hand this off to a friend of mine who loves protocol reversing.

**Comment by finger563** [comment]
any update on this?

**Comment by timmeh87** [comment]
The most detailed resource to date is here

https://github.com/dekuNukem/Nintendo_Switch_Reverse_Engineering

**Comment by mfosse** [comment]
This is for the most part done, so I'm going to close this.
