### ISSUE TITLE
Both Joycon Sticks Slightly Broken

### ISSUE THREAD

**Issue by NoThisIsStupider** [mfosse/JoyCon-Driver#17]
For some reason, both sticks values are messed up, and alternate constantly between the value you expect and a value far lower. This can easily be seen in the joy.cpl calibration screen. It seems to mess with the overall calibration and the effects can be seen in some games, even after going through XOutput. The problem can be found in both Combined and not Combined, which makes me think there's an error in how the stick values are read.

**Comment by mfosse** [comment]
is this still an issue?
