### ISSUE TITLE
Step 2 Broken Link

### ISSUE THREAD

**Issue by linktlh** [mfosse/JoyCon-Driver#18]
On step 2 "Setup your vJoy Devices to look like this:
the first link is broken... I'm assuming its not the same setup as link 2 because I couldn't get the driver to work.

**Comment by NoThisIsStupider** [comment]
Basically just enable controller 1, and give jt 32 buttons. I just checked the image myself, and it looks to be working though, can you check again?

**Comment by linktlh** [comment]
![a2ab85bc3cca3bc9a7c746a52be12bc6](https://user-images.githubusercontent.com/15271738/27765937-a550e8a4-5e85-11e7-89b5-a73554a4fe5e.png)

**Comment by NoThisIsStupider** [comment]
I don't know what to tell you, I opened your image, typed the url into my browser, and I got the vJoy config image. Whatever it is, it's on your side it seems. More proof of this is that imgurs can't find image in url page looks like this and not a 404 page: 
![image](https://user-images.githubusercontent.com/28993090/27765958-7d742450-5e8e-11e7-9f44-c34c7a235355.png)

**Comment by linktlh** [comment]
oh well. Heres full report. xD http://imgur.com/a/KzWXP The problem I have now is the Right Joy-con light indicator doesn't stop flashing. it's probably something I did wrong but anyway to fix this?

**Comment by mfosse** [comment]
It can take a few times before the lights go solid, but if they don't the program works anyway, the lights are purely aesthetic
