### ISSUE TITLE
joysticks left max elongation === max right elongation

### ISSUE THREAD

**Issue by uani3** [mfosse/JoyCon-Driver#19]
For both JoyCons maximally pushing the joystick left (vertical layout each hand) gives maximal right input to the game I'm playing. Could also be the games controls settings manager but other joysticks / gamepads work or vJoy.

I have got the neon yellow JoyCons.

**Comment by uani3** [comment]
on the other hand vJoys monitor doesn't show this behaviour with the JoyCons. But I checked the game and it doesn't show the behaviour with a dedicated joystick.

**Comment by mfosse** [comment]
Are you using x360ce? You might just have the stick reversed in the settings. There's also commands to reverse the sticks' axes

**Comment by NoThisIsStupider** [comment]
To add to that, try using XOutput instead. It's far easier to set up and doesn't need per game dll installation. Here's a config for XOutput:

https://i.imgur.com/0mTdUH8.png

**Comment by mfosse** [comment]
thanks for the suggestion @NoThisIsStupider, I hadn't heard of XOutput before this.
