### ISSUE TITLE
Important input lag

### ISSUE THREAD

**Issue by Kyrio** [mfosse/JoyCon-Driver#23]
There seems to be non-negligible latency (roughly half a second) between the moment a button is pressed and the moment the vJoy driver handles the input, as seen for example in `joy.cpl` or Dolphin's controller settings. I haven't seen this discussed here, is it a common issue?

**Comment by NoThisIsStupider** [comment]
Do you have a desktop? If I have my Bluetooth dongle (it's very small, so the range is bad, small antennae) plugged directly into a USB port on my desktop, I experience this problem. However, if I use a USB-A Male to USB-A Female (One comes with the steam controller), and move the Bluetooth dongle far enough away from my computer, I have 0 lag. If your Bluetooth is built into your computer, maybe buy a USB one (go for a big one for better range), and buy a USB Male to Female.

**Comment by Kyrio** [comment]
I'm using the native Bluetooth adapter on my laptop. It's the first time I get latency problems with a Bluetooth controller though, including Wiimotes with Julian Loehr's driver. Do you think it's an interference problem?

**Comment by NoThisIsStupider** [comment]
Wiimotes work fine with my bluetooth adapter plugged directly in too. The Joycons just have awful built in bluetooth.

**Comment by mfosse** [comment]
There's an issue already for this, please don't make a new issue when one for the same topic already exists, thx.

**Comment by Kyrio** [comment]
I've checked before, of course, but my eyes were probably not working at the moment. Sorry for the trouble!
