### ISSUE TITLE
DLL Files Missing!!!

### ISSUE THREAD

**Issue by RarePika** [mfosse/JoyCon-Driver#24]
So, I stumbled across this tool today. I downloaded it and tried to run it. I found myself at these windows:
![time](https://user-images.githubusercontent.com/17325905/27953222-027e85a8-6346-11e7-8c0a-9c6e4cc1bc0c.png)
How do I fix this issue? Do I need to install an extra program? Do I have all the right files?
![problem](https://user-images.githubusercontent.com/17325905/27953259-21acefc8-6346-11e7-8a55-a1ef33d2a356.png)
Please help! I really want to try this driver out!

- Thanks!
RarePika

**Comment by RarePika** [comment]
I forgot to mention, I run a Windows 10 64 bit laptop.
![cpu](https://user-images.githubusercontent.com/17325905/27953513-0e2d3434-6347-11e7-959f-b32bd2ea5fe7.png)

**Comment by ttay24** [comment]
Did you just download a release (rather than building project on your own)? Looks like it was compiled in debug mode, but you don't have visual studio 2015

________________________________

**Comment by claymullis** [comment]
This has come up before and was supposed to be resolved. Looks like they got recompiled in debug mode accidentally. One (very time consuming) solution is to download Visual Studio 2017 Community from https://download.visualstudio.microsoft.com/download/pr/10811651/045b56eb413191d03850ecc425172a7d/vs_Community.exe

`sh
git clone https://github.com/mfosse/JoyCon-Driver.git
`

Then, open up the Visual Studio solution file. If a dialog appears asking if you'd like to use a "version checker" (can't remember the exact wording), make sure to do that as the project is built with Visual Studio 2015. VS 2017 is what's most available and it's backwards compatible from what I've tried. 

Anyway, from VS you can go to Build > Release (or debug or if you're coding) and the necessary files should show up in the same place you used to find them in the repository. 

* Sorry if this is inaccurate. Currently on Linux and can't reproduce the install.
