### ISSUE TITLE
Either left or right joycon stops working and disconnects after a minute of opening joycon-driver.exe

### ISSUE THREAD

**Issue by RevvOcelot** [mfosse/JoyCon-Driver#27]
I'm so excited to use your driver, please answer if you can >_<
To give some background, both of the JoyCons work fine by themselves, but the moment I open joycon-driver.exe, it all works fine, and after 30 - 60 seconds either the left or the right joycon just stops responding and usually disconnects it from the bluetooth as well.
This is what i'm getting from the CMD.

> 

vJoy device 1 is free
Acquired device number 1 - OK
vJoy device 2 is free
Acquired device number 2 - OK
Found joycon L 0: UnKnownFound joycon R 1: UnKnownEnabling vibration...
Enabling IMU data...
Increase data rate for Bluetooth...
Pairing1?...
Pairing2?...
Pairing3?...
Successfully initialized Joy-Con (L) !
Enabling vibration...
Enabling IMU data...
Increase data rate for Bluetooth...
Pairing1?...
Pairing2?...
Pairing3?...
Successfully initialized Joy-Con (R) !
setting LEDs...
vibrating JoyCon(s).
Done.
0.0000
0.0617
0.0000
0.0000
0.0000

Then i'm just endlessly bombarded with 0.0000 messages.
Do you think this could be a problem with my bluetooth? I don't really think so because of what I mentioned earlier.. I was playing with Dolphin really nicely, and when I turned on joycon-driver.exe it was way more fun obviously, but one JoyCon just randomly stops working..
More info, when I connect my JoyCons to the Bluetooth, they start flashing up and down like they should. They keep on doing this for pretty much forever, which is definitely normal. As soon as I open joycon-driver.exe the lights stop, by that I mean its still lit but it isn't moving up and down. Only 1 cube is lit.  When the error occurs and one of the JoyCons stop working, the lights either start going up and down again or just turn off completely. Then if I check my Bluetooth, that joycon is disconnected and I have to connect it all over again.

**Comment by theofficialgman** [comment]
I also have this problem. Same issue, same situation. Just to note sometimes when one disconnects I have to do the pairing all over again.

**Comment by RevvOcelot** [comment]
Exactly, already said that lol. Glad to see i'm not the only one xD

**Comment by jabujabu** [comment]
Same for me

**Comment by jabujabu** [comment]
Anybody has work around for this yet? Now I got workaround for everything only except this one which make us can't stably play the game.

**Comment by mfosse** [comment]
@jabujabu I don't know why this happens for some people, my guess is bluetooth connectivity issues, it's hard to debug since it doesn't happen to me;

If I were you I'd probably get an external bluetooth adapter (if you are using an internal one like on a laptop) or if you are already using an external adapter maybe get a different one, this is the one that I use: https://www.amazon.com/Plugable-Bluetooth-Adapter-Raspberry-Compatible/dp/B009ZIILLI/ref=sr_1_1/146-0027820-3965552?ie=UTF8&qid=1504102371&sr=8-1&keywords=plugable+bluetooth+adapter

please let me know if changing the adapter fixes your issue / list your current adapter

**Comment by jabujabu** [comment]
thanks for the answer and it worked!! no more disconnect. My model is "NEXT-104BT". I had used intergrated bluetooth in my window tablet before. But there is still input delay on master build even with new bluetooth dongle.(holleyjean's build is OK on both bluetooth). at least I have all solution for almost issues, Thanks!!!
