### ISSUE TITLE
Add a GUI

### ISSUE THREAD

**Issue by mfosse** [mfosse/JoyCon-Driver#28]

**Comment by mfosse** [comment]
I'm looking into possibly using qt5 or wxWidgets to make a GUI rather than the whole command line mess

**Comment by NoThisIsStupider** [comment]
If a gui is made input remapping should be finished and added to it, i'm gonna start taking a look into both input remapping, and xinput directly implemented into this driver soon, using the recently open-sourced Wiinupro to help me work through the issues I ran into (I've never worked on this kind of thing before).

**Comment by mfosse** [comment]
I've mostly finished the GUI (for now), but I still don't understand why remapping the buttons is necessary since the program uses vJoy and the numbers are completely arbitrary @NoThisIsStupider please explain

**Comment by NoThisIsStupider** [comment]
Some games don't like XInput, Sonic CD 2011 for example, unless we bypass vJoy altogether and just use XInput. Either way freedom is nice.
