### ISSUE TITLE
Work with More Than Two Controllers

### ISSUE THREAD

**Issue by thehenoch** [mfosse/JoyCon-Driver#30]
If you have two pairs of controllers (4 in total), you cannot combine the second set into a second combined controller. Also, currently, the four can not all be added as controllers, instead the last two added are ignored.

**Comment by mfosse** [comment]
this should be pretty easy to add, but combining the second set of controllers might be a bit tricky. I'll probably just set it up to use vJoy devices 3 & 4 if they are detected, but it might be a while before I combine them, ideally I'll make a controller system like the switch has, but that'll take a while.
