### ISSUE TITLE
My mouse is getting stuck in the upper right corner when I enable gyro controls

### ISSUE THREAD

**Issue by yrostaqi** [mfosse/JoyCon-Driver#31]
I can move my mouse but it gets back really quickly to the upper right corner of the screen. I have to Alt-F4 the application if I want to use my mouse again.

Plus when I watch the vjoy monitor while the gyro functions are enabled only the left joy-con's inputs are recognized. And I don't know where to check if the gyroscope functions are working either (the monitor doesn't show anything more than the left joy-con's buttons).

![capture](https://user-images.githubusercontent.com/31565280/30128736-04d63b92-9344-11e7-9b0b-69cc638b1e39.PNG)
![capture2](https://user-images.githubusercontent.com/31565280/30128735-04d40836-9344-11e7-807b-277fe9db8034.PNG)

I hope that someday I will be able to play Dolphin (Wii) games with this. 👍

**Comment by facekapow** [comment]
Yeah, I second that. My mouse just shoots up to the top right corner of the screen when enabling gyro. The problem I have with it is that it won't move, no matter what. I think mouse control should optional and should be behind a flag (`--mouse`).

**Comment by mfosse** [comment]
This is a bug that I'll probably fix after hurricane Irma passes and I get back to my apartment / PC

**Comment by facekapow** [comment]
@mfosse Sorry to hear that, hope you stay safe 👍
