### ISSUE TITLE
Enabling Gyro controls doesn't seem to do anything

### ISSUE THREAD

**Issue by ballerfuturistic** [mfosse/JoyCon-Driver#32]
Heya,

Enabling Gyro controls doesn't seem to do anything. I see output to show that they're moving in the cmd window that opens -- but it doesn't seem to move my mouse or anything.

Is this intended or did I miss a step?

Thanks!

**Comment by mfosse** [comment]
Yeah it's disabled right now since there have been a lot of new developments in terms of the gyroscope and accelerometer recently and I'm in the middle of implementing the changes, it wasn't in a working state before anyways. I'm also working on a 3D cube real-time visualizer of the joycons gyroscope

**Comment by mfosse** [comment]
The reason I don't just not commit these changes until it's done is because I work on multiple devices (laptop and desktop) and I use github to sync the changes between the two. It's also why I have a bunch of commits labeled saving lol.

**Comment by ballerfuturistic** [comment]
That's perfectly fine!

If you need a hand, my friend NTAuthority might be interested in helping.
(he'll probably check it out anyway tbh, i think!) -- he's the dude who reversed GTA:Online way back long ago and got taken to court by TTwo over it.

Any chance I might be able to get you on Discord? Maybe we can help out.
Mars#1305 if you'd be willing to add me :)

As a side note, input lag is definitely way better with that bluetooth dongle you suggested in another issue, though I suspect the issue was more so with the front ports of my computer -- as if they didn't properly power the USB Bluetooth (I had the same issue with a controller in the front port, so)
