### ISSUE TITLE
Skip unnecessary files commit

### ISSUE THREAD

**Issue by CTCaer** [mfosse/JoyCon-Driver#33]
Currently the .gitignore is commented so it commits almost everything especially the unnecessary db.

The best way to have clean commits, reduce the repo size and still keep build releases, is to use the default .gitignore and just comment the following line.
https://github.com/mfosse/JoyCon-Driver/blob/f71e5d9a995d5148ff25359492c5574702e2da02/.gitignore#L19
Or even specialize it to only commit the needed exe/dll/txt, without symbols/object files.

This way, you don't lose anything. You can still download repo, fire the project and build right away.
Additionally, having clean commits, will also help you with the saving style you have, reminding you easily/cleanly what you changed between your PCs.
And for users, easier follow up of the project.

If you don't have time, I can arrange a PR.

**Comment by mfosse** [comment]
I've been meaning to update my .gitignore file for a while now, thanks
