### ISSUE TITLE
Support for Pro Controller

### ISSUE THREAD

**Issue by timmeh87** [mfosse/JoyCon-Driver#34]
I have a Pro joycon controller, but the driver does not detect it. Looking into the code, I can see this block

```
			// pro controller:
			// (probably won't work right, I'm just putting this here so it detects it,
			// I don't have a pro controller to test with.)
			if (cur_dev->product_id == PRO_CONTROLLER) {
				found_joycon(cur_dev);
			}
```

Right away, it seems odd to me that the above block for joycon R and L has this line, but the Pro block does not

`settings.usingBluetooth = true;`

If you wanted to test out some pro controller related code, I can try to run it. I would like to have this working and I think it should be pretty simple.

Im actually connecting a home-made joycon emulator, not a real controller. and I can make the actual Switch console think im either a R, L, or Pro device by changing a single byte, so I don't think there is much difference code-wise as far as parsing the data and this should be an easy feature to add .
(and of course, it works fine with your driver as long as it appears to be a L or R joycon)

**Comment by mfosse** [comment]
I just haven't gotten around to fixing it yet (because I don't have a pro controller), thanks for making the Issue, I'll see if I can fix it soon and I'll make a comment here when I'm done / ask you to test it

**Comment by timmeh87** [comment]
I did a scan through the code and I have this suggestion:

right now you have a concept of left and right, where left == 1 and right == 2. This could be conveniently viewed in binary as a bit for left, and a bit for right. So if you have a third option, == 3, that would be like setting both the left and right bits at the same time. Instead of checking for == 1 or == 2, you would check for & 0x01 and & 0x02 

The joycon structure itself should probably be able to represent a full (pro) joycon. It looks like you do have fields for a "stick2" in there already. Then it should just be a few more changes to the parser so it has the option to parse both sticks and both button fields instead of either-or. There is an option to "combine joycons" so I assume you could ride off of that logic.

I admit, now it is starting to seem like a bit of work to do blindly. I might be able to help one day but I have to get widgets and QT and all that to compile and a lot of my real job to do

**Comment by mfosse** [comment]
I've added basic Pro Controller support, let me know what does and doesn't work

**Comment by timmeh87** [comment]
Wow that was fast! Heres a quick shakedown:

> Start in default mode (Combine, Auto Center, Gyro Window)
> console states both vjoy devices acquired, Pro Joycon is found and supposedly initialized (I can check if that is true later but this is a "quick shakedown")
> console gets to "Auto centering sticks..." 
> Gyro viewer window crashes  (window is all white, title bar says "not responding"
> I open the "Monitor Vjoy window" and everything crashes including the driver
   > Back to this step on a second attempt, it actually only crashes after I press any button on the controller (what I refer to as my "fake joycon")

The ultimate vjoy crash gives the message "joycon-driver.exe has stopped working" with the standard boilerplate error about "a problem"

**Comment by timmeh87** [comment]
Opening vjoy monitor has nothing to do with the crash, Vjoy is not crashing and it crashes without having any vjoy windows open.

I tried to debug the application using VS2013 and VS2015 but it is not accepting the PDB file for some reason. I point the debugger right at it and it says something like "a matching symbol file was not found"

I noticed that the PDB file I have is actually old, it is no longer on github, just an .ipdb file, which is way too small to be a real file (quick google suggests this is some newfangled incremental linking feature)

I think I am unable to debug because I have an old PDB file. Maybe if you put the PDB from the same build as the EXE onto github, I would be able to debug the source code

Also since it is a "release" build it might be built with no symbols? I think it is still possible to output PDB files with a release but IIRC there is something about releases that makes debugging harder. I think the optimization level maybe.

**Comment by mfosse** [comment]
Interesting, I have classes untill 4 so I'll look at it further then, this was just a quick hack I made in like a half hour I had between classes

**Comment by mfosse** [comment]
@timmeh87 can you try compiling/running in VS 2017 and telling me where it crashes / why?

**Comment by Uumas** [comment]
![2017-11-19 20_50_09-joycon debugging - microsoft visual studio](https://user-images.githubusercontent.com/10895201/32994110-6b2a9936-cd6b-11e7-9840-27ef5a37b0b2.png)
That's what I get when trying to run this with the Pro Controller. I'm not too familiar with programming, so I'm not sure if this helps, but I hope it does.

**Comment by timmeh87** [comment]
Hey sorry, I sorta disappeared there. Other projects have taken all my time. That error to me looks like "gyro_data" is undefined perhaps? the previous IF statement is used to put a memory address into "gyro_data". Is it possible it does not hit that because left_right does not ==1 or ==2

**Comment by mfosse** [comment]
@Uumas thanks, this helps a lot, actually and what @timmeh87 said sounds about right, Im busy today though so probably won't look into it until tomorrow

**Comment by Uumas** [comment]
![2017-11-20 21_26_47-joycon - microsoft visual studio](https://user-images.githubusercontent.com/10895201/33037295-bf7d1274-ce39-11e7-9af4-f57f65df681c.png)
You were correct @timmeh87 Adding an else to it like this fixed it. Everything seemed to work as it should.

**Comment by mfosse** [comment]
@Uumas @NoThisIsStupider @timmeh87 I've implemented this fix in the latest push, let me know if there are any other problems, also if you could test using the joycons + procontroller together to see if it works as intended or not.

**Comment by Uumas** [comment]
The buttons I mentioned above still don't work.

**Comment by chfo** [comment]
@Uumas do you have a fix for the missing buttons or is it still broken?

I try to get into the code and look why :-)

**Comment by Uumas** [comment]
Sorry, no idea...

**Comment by mfosse** [comment]
so L, ZL, D-Pad and left joystick don't work? that's pretty hard to debug without a Pro Controller to read the output from. I'll see if I can get one soon (once I do it should be pretty easy to figure everything out)

**Comment by mfosse** [comment]
@timmeh87 @Uumas @timmeh87 
in the mean time I'm setting up some special output in debug mode in the latest build for the pro controller it'll just be some numbers, I need someone to confirm that the number changes anytime a button pressed, if there is a button (or key combination) that causes the numbers to not change, let me know

**Comment by timmeh87** [comment]
hey whats up, sorry about the long delay

When i connect a pro joycon in debug mode, I see a new set of numbers appear whenever I press a button or move a stick. All left side buttons affect the first number, all right side buttons affect the second number. The sticks do not show up, so moving them just brings up a wall of "0, 0".

In vjoy, the left side buttons still do not appear

**Comment by timmeh87** [comment]
Maybe check this section:

```
	// Set button data
	// JoyCon(L) is the first 16 bits
	// JoyCon(R) is the last 16 bits

	long btns = 0;
	if (!settings.combineJoyCons) {
		btns = jc->buttons;
	} else {

		if (jc->left_right == 1) {
			btns = ((iReport.lButtons >> 16) << 16) | (jc->buttons);
		} else if (jc->left_right == 2) {
			btns = ((jc->buttons) << 16) | (createMask(0, 15) & iReport.lButtons);
		}
	}

	// Pro Controller:
	if (jc->left_right == 3) {
		btns = ((iReport.lButtons >> 16) << 16) | (jc->buttons);
		# btns = ((jc->buttons2) << 16) | (createMask(0, 15) & iReport.lButtons);
	}

	iReport.lButtons = btns;
```

btns is overwritten

**Comment by mfosse** [comment]
@timmeh87 that section is only relevant for the data being put out to vJoy, but I can't do that yet since I don't know how the pro controller data is formatted

Right now I'm just trying to get the debug printout working, then I'll parse the data into vJoy

If the debug printout is how you say it is, then I'm pretty lost and will probably just need to buy a pro controller

Basically what's there is just a guess, (it is incorrect, though)

**Comment by timmeh87** [comment]
but when I connect a pro controller, data _is_ going to vjoy. My pro controller's entire right-hand side works already. And the left-side buttons are appearing in debug mode, so it looks like we are getting them into buttons2

it looks like to me that in the part I pointed to above, the right-side buttons (the same line of code from jc==2) are directly overwriting the left buttons (same code from jc==1). This is suspiciously exactly the same thing that seems to be wrong with the vjoy feed. Maybe not a coincidence?

**Comment by mfosse** [comment]
The left and right side might be reversed, let me know if that's the case

(The left side of the controller should trigger the first 16 buttons and the right side should trigger buttons 17-32)

**Comment by mfosse** [comment]
Looking at the code, I realize the debug mode for the pro controller is barely there, I'm going to update it to print out two numbers, in binary I want you to note which button corresponds to which digit in the string turns in to a 1 when pressed

This will let me make a debug printout for pro controllers

**Comment by timmeh87** [comment]
Im confused.. it does print out two numbers. the right-hand number was the right-side buttons, and left-hand number is the left-side buttons. That seemed to make sense to me. 

Now when i play with it, the feed of numbers keeps going constantly. idk why it was stopped before.

Keep in mind, this is actually a generic gamepad controller so Im not sure if that is going to map the same as a joycon.. I think i tried to keep the mapping as sensible as possible. this setup worked on the switch console okay

While I was typing that, the feed of numbers stopped again, it only advances when I push a button. Weird. 

Ok well here I go. use picture of xbox controller for button locations

L1 - (64, 0)
L2 - (128, 0)
l3 - (2048, 2048)
R1 -(0, 64)
r2 - (0, 128)
R3 - (1024, 1024)
a - (0, 4)
b - (0, 8)
x -(0, 1)
y - (0, 2)
V - (1, 0)
^ - (2, 0)
> - (4, 0)
< - (8, 0)
two squares (menu??) - (256, 256)
three lines (..menu??) - (512, 512)

sorry for also not having a real pro controller and not knowing the names of buttons, lol.
