### ISSUE TITLE
Gyro controlls cursor drift

### ISSUE THREAD

**Issue by Migushthe2nd** [mfosse/JoyCon-Driver#39]
When using Gyro controlls the cursor slowly moves to the left. It's probably gyroscopic drift, but for some reason it never stops, no matter how long you wait.

**Comment by Migushthe2nd** [comment]
It has become even worse using the source code. I just noticed this.

**Comment by mfosse** [comment]
I'll work on the gyro controls a bit more after exams

**Comment by Reizake** [comment]
Hello! Having the same problem. I like the function to control the mouse but its near unusable with the drift.

**Comment by mfosse** [comment]
The best you can do right now is lower the sensitivity and use the gyro combo code to turn on/off gyro controls, at least until I get the chance to get the calibration with gyroscopes working.

**Comment by xantyleonhart** [comment]
The only thing screwing up the gyro controls is you using the accelerometer. Just remove the accelerometer part and stick just to the gyro. I had a similar problem before with another project involving a cell phone. When you use an accelerometer to calculate a position you have to integrate twice (once to get the speed from the acceleration, and again to calculate the position), this means that a very small error in the measuring of the sensor can grow exponentially on its own over time, causing your mouse to suddenly move on its own or jitter like crazy.

There are techniques you can use to try to correct the noise, like storing a temporary array of measurements and using the standard deviation, or using a low-pass filter for very low acceleration values, but i assure you that it is ultimately useless and not worthwhile when you could just use the gyro to track distance/rotation.

**Comment by mfosse** [comment]
@xantyleonhart thanks for the advice, but the Accelerometer isn't currently used for the mouse controls option, it's only used for the 3D die

**Comment by mfosse** [comment]
@xantyleonhart the problem is caused since calibration data isn't taken into account (yet)

It's on the to-do list but I won't make any promises until I have more time

**Comment by xantyleonhart** [comment]
uh, ok. I assumed it was working on both cases, and it seemed weird for the gyro to cause that erratic movement. I just gave the code a really quick look so i must've overlooked it. Nice job though, and keep up the good work!

**Comment by xantyleonhart** [comment]
I fiddled a little with the code trying to fix it and i somewhat got it to work decently for my joycon, but i didn't have much time to look at all those lines of code in depth and i don't have experience coding drivers aside from toying with some arduinos so i think it's more of a  crappy patch, but if you want to take a look at it i'll leave the link here:
https://github.com/xantyleonhart/JoyCon-Driver/tree/master/joycon-driver

Don't mind the "Q?", i had some trouble with the Vim editor when trying to commit. 
HOW IT WORKS:
I made it so you have to leave it on a surface without moving for a few seconds until it calculates enough data to calibrate the joycon, then you can move it, the console will print it on the screen by default.
As a result, the sensitivity has been affected, so i reccomend, lowering it down to around 30 so it works properly.

--------SUMMARY of my edits:
I just made it load a bunch of measures on buffers and then calculate the mean of those buffers for each of the axes, to correct the offset values that kept showing on the joycon by default on resting position (at least it happened on mine). After that, use the same buffers to calculate the standard deviation and divide the following input by the standard deviation to try to reduce possible stuttering.

**Comment by mfosse** [comment]
@xantyleonhart Thanks I really appreciate the work & especially the summary of the edits, I'll take a look at it soon

I've been meaning to work on calibration data, and thought about doing something similar to what you did (I did something similar for stick data originally before I got the calibration data), but didn't have the time.

**Comment by mfosse** [comment]
@xantyleonhart @Migushthe2nd @Reizake I finally made use of the calibration data in the latest update so there shouldn't be any more drift (unless you set the sensitivity really high), and it should be much more accurate now
