### ISSUE TITLE
setting for autodetecting offsets at start.

### ISSUE THREAD

**Issue by My1** [mfosse/JoyCon-Driver#4]
would be awesome if some kind of `--auto` or whatever could be passed which assumes that the sticks are in neutral upon start/Connect and sets the offsets acting on the detected stick's values.

by the way, this is exactly how nintendo handled their controllers' sticks for a while (I know from Gamecube and Wii personally, dunno about the rest) so wouldnt even be that weird to introduce that.

another way would be a calibration application where you do the usual (conform the middle position of the stick, and rotate in fully) to understand the Stick's data and store the data along with the Hardware-ID into a config file.

**Comment by mfosse** [comment]
this is a pretty good idea, thanks! I'll make it center the sticks automatically with --auto-center soon.
soon I'll probably make the program use a config file rather than all these parameters too.

**Comment by theofficialgman** [comment]
I am reopening this issue because auto centering appears to not work, whenever I run autocenter, both joycsticks appear to be off by quite a bit.
