### ISSUE TITLE
Left joystick not working

### ISSUE THREAD

**Issue by Migushthe2nd** [mfosse/JoyCon-Driver#40]
The left joystick doesn't seem to be working anymore. I tried an older version and the stick worked just fine.

**Comment by mfosse** [comment]
How many joycons were connected? Which settings?

**Comment by NoThisIsStupider** [comment]
Also reporting a broken left analog. Latest version from downloading the github repo and running the exe in the release folder, and the only setting checked is combine joycons, nothing else.
