### ISSUE TITLE
Left JoyCon analog stick doesn't seem to work

### ISSUE THREAD

**Issue by DVDLessa** [mfosse/JoyCon-Driver#41]
The right JoyCon analog stick does work fine, like any other button from both JoyCons.
But the left ones analog stick just doesn't. The button from analog work aswell.

On vJoy Monitor, the right X,Y,Z moves nice, while the left X,Y are stuck in the middle, and Z on the bottom.
![image](https://user-images.githubusercontent.com/33708156/32871558-ef16a466-ca68-11e7-87cc-5c7811bf9c9c.png)

**Comment by mfosse** [comment]
this is fixed in the latest build

**Comment by DVDLessa** [comment]
Fixed.
