### ISSUE TITLE
Separate joy cons don't seem to work

### ISSUE THREAD

**Issue by Sheeraudacity** [mfosse/JoyCon-Driver#49]
I just downloaded this application 2hrs ago and it seemed to have no trouble when I combined the joy cons (I haven't really tested it, but the gyro seemed to detect my joy cons' feedback and it showed on vjoy monitor), however when I tried to use the joy cons individually they decided they want to connect to devices 0 and 3. 3 was no problem, 0, on the other hand, I had no idea how to connect to. I then closed the application, vjoy and disconnected the joy cons then connected them again and opened the application first hoping it will register them to vjoy automatically, but it told me I had to open vjoy and when I opened it I was right back at where I started.I then checked the config for an option to change which vjoy device the joy con would connect to, except there was no such option. There's probably an easy fix for this but I have been racking my brain for a while and I have absolutely no idea.

**Comment by mfosse** [comment]
fixed in the latest release
