### ISSUE TITLE
Joycon autocentering not working properly

### ISSUE THREAD

**Issue by theofficialgman** [mfosse/JoyCon-Driver#5]
whenever I activate joycon autocentering both joysticks are off center by a fair amount. I believe center should be somewhere around 16384 but I am getting readings of left stick X -2696 Y 3144 and right stick X 18360 and Y 15640 and these results are consistent over multiple trials

**Comment by theofficialgman** [comment]
just to note, without autocentering I get readings of left stick X 15280 Y 15400 and right stick X 18360 and Y 15640

**Comment by mfosse** [comment]
oops! I made a last minute change that broke the whole thing! lol, thanks for notifying me!

**Comment by mfosse** [comment]
I've updated the repo so I'm going to re-close this issue
