### ISSUE TITLE
Cannot run application

### ISSUE THREAD

**Issue by CNEpicness** [mfosse/JoyCon-Driver#51]
I do not see what to run.When I open joycon-driver in:
JoyCon-Driver-master\JoyCon-Driver-master\joycon-driver\build\Win32\Release
I get the error message:
"The program can't start because MSVCP140.dll is missing from your computer. Try reinstalling the program to fix this problem."

**Comment by ttay24** [comment]
I think you’re missing the C++ visual studio 2015 runtime

________________________________

**Comment by CNEpicness** [comment]
It works, and the JoyCon R is giving a gyroscope input with the dice. Thank you!
