### ISSUE TITLE
vJoy Monitor and dolphin emulator not showing any output from the joycons when used as wiimote

### ISSUE THREAD

**Issue by CNEpicness** [mfosse/JoyCon-Driver#52]
The gyroscope works as shown in the 3D Joycon gyroscope visualizer, but the vJoy monitor shows no inputs. The same result occurs when trying to configure a wiimote

**Comment by mfosse** [comment]
It sounds like vJoy isn't setup correctly? Does this only happen when used with dolphin?

**Comment by CNEpicness** [comment]
It only happens with dolphin, but I haven't tested it with anything else. What else should I test it with?
