### ISSUE TITLE
api-ms-win-core-rtlsupport-l1-2-0.dll is missing

### ISSUE THREAD

**Issue by SimonDKiller** [mfosse/JoyCon-Driver#53]
When i try to start the app, i get an error who said that i don't have this dll. How can i repair this?

**Comment by ttay24** [comment]
Which dll? Can you send a screenshot of the error?

________________________________

**Comment by SimonDKiller** [comment]
It's in the title, but ok...
![dll missing joycons 1](https://user-images.githubusercontent.com/1256145/34644234-5a59fc5e-f300-11e7-80c8-b9b06f1538f8.png)

**Comment by ttay24** [comment]
Sorry, read too fast haha. Thanks. What version of Windows are you running?

________________________________

**Comment by SimonDKiller** [comment]
Windows 7

**Comment by ttay24** [comment]
Windows 7 isn’t supported at the moment:
https://github.com/mfosse/JoyCon-Driver/issues/48
