### ISSUE TITLE
R Joycon disconnecting

### ISSUE THREAD

**Issue by RandomAnimeGamer** [mfosse/JoyCon-Driver#55]
Hey there! It seems that for whatever reason my right-hand joycon keeps disconnecting after a while on the latest build as of now.

This only seems to happen when I'm running the feeder and I noticed the GUI tends to crash a lot as well. I've tried two different bluetooth adapters and the problem persists.

Edit: Oh yeah, I should mention my specs.
Windows 10 (64-bit)
i5-6500
8GB RAM
AMD RX 460

**Comment by mfosse** [comment]
How exactly does the GUI crash? is there a specific error?
Which bluetooth adapter(s)?
