### ISSUE TITLE
Connecting to MC

### ISSUE THREAD

**Issue by DatBoi124** [mfosse/JoyCon-Driver#56]
So, i used this and everything worked, it linked to X360. However, I cant figure out how to connect X360, or the joycon driver to MC.. 

(on Windows)

Any fixes or maybe i should use some other program?

**Comment by mfosse** [comment]
By MC do you mean Minecraft?
From what you have said, the program is working fine, you just need to setup x360ce with MC

**Comment by DatBoi124** [comment]
Ok. Thanks! Any idea how to do this? I’ll post it on the x360ce forums if not.

Thanks again.
