### ISSUE TITLE
I've done everything the instructions told me to do, however, my buttons wont work. They won't be mapped neither. 

### ISSUE THREAD

**Issue by RadonBlade** [mfosse/JoyCon-Driver#59]
When I downloaded that XBOX 360 controller emulator to map my buttons to, it wouldnt even respond there. My cons are connected to my computer also already bluetooth wise. So what could I be doing wrong? I'm in need of assistance.

**Comment by mfosse** [comment]
does it work with vJoy?
if you didn't install vJoy, you need it for it to work.
if your problem was related to unchecking "combine Joycons", it's fixed in the latest update

**Comment by iiPostMaster** [comment]
i'm having the same problem and i have vJoy installed
