### ISSUE TITLE
Error 0xc000007b after getting dll needed

### ISSUE THREAD

**Issue by lIlHelpWantedlIl** [mfosse/JoyCon-Driver#60]
I have been attempting to use the program you released all day, originally it said I did not have the dll installed, MSVCP140.dll, so I thought it may work if I completely updated my laptop. I am currently running Windows 8.1 Pro 64 bit as well. I had updated it completely, made sure the right redistributables were installed, made sure the .NET Framework was fully updated up to 4.7.2, and I deleted and redownloaded the program numerous times, but I continuously had gotten an error saying I am missing MSVCP140.dll. I went online, found, and downloaded it, and now I have the error 0xc000007b. I was wondering if there was any fix for this, if it was the bit version I'm using or what. I would very much appreciate a response. Thank You!

**Comment by Craftyawesome** [comment]
You might need to install the visual studio runtime. Did you download the whole folder with all the dlls? Don't download dlls online as they are basically exes.
