### ISSUE TITLE
Support for more than 2 joycons

### ISSUE THREAD

**Issue by senritsu** [mfosse/JoyCon-Driver#61]
Currently it appears (please close this issue if i am wrong) that only one pair of R/L joycons is supported.

It would be very handy if more than 2 joycons could be used, for things like 4 player local multiplayer titles.

**Comment by mfosse** [comment]
More than 2 joycons is already supported, up to a max of 8

**Comment by senritsu** [comment]
ok, thanks for the clarification. I must have done something incorrectly then.
