### ISSUE TITLE
How to reverse Gyro controls?

### ISSUE THREAD

**Issue by TsundereBug** [mfosse/JoyCon-Driver#67]
Pitching the joycon downwards moves the mouse upwards, yawing the joycon left moves the mouse right, etc. How to reverse these?

I have already tried setting sensitivity to negative.

**Comment by mfosse** [comment]
It's interesting that setting the sensitivity to negative didn't work, but I haven't added the feature to reverse the directions yet, I'll can probably add the feature sometime tomorrow though
