### ISSUE TITLE
Second connected Joycon has input lag

### ISSUE THREAD

**Issue by ctrexler** [mfosse/JoyCon-Driver#70]
Whichever Joycon I connect to my PC via bluetooth (Left or Right), the one I connect second always has about a second or two of input lag while the first works just fine. I've been fighting with this for months but decided to finally submit as an issue. Nobody else seems to be experiencing it though. I run Windows 10 if that matters.

**Comment by ctrexler** [comment]
My apologies, I just now saw this was already submitted under "Closed Issues". I was dumb and didn't notice the main issues list is only open issues. I will continue my discussion on the other Issue should I need to.

I would've deleted this issue but I don't see any options to do so.

**Comment by mfosse** [comment]
@ctrexler I'd classify this under issue #2 but it's important that you provide details

What bluetooth adapter do you use? Or, if it's internal (like on a laptop) what laptop? You said you've been fighting with this for months, is it consistently laggy or is it on-off?

**Comment by ctrexler** [comment]
It sounds more like issue number 42 to me, which your solution there actually solved my issue. I'm all good now, and I appreciate your work on this project greatly! Thanks!
