### ISSUE TITLE
Gyro calibration data not being used as offset

### ISSUE THREAD

**Issue by JibbSmart** [mfosse/JoyCon-Driver#75]
Hi Matt, it's me again.

We talked before about how I thought the factory and user sensor calibration data are supposed to be used as offsets for the raw sensor input (rather than multipliers), and now I'm more confident this is the case.

When I calibrate my JoyCons using the Switch's system settings, the user sensor calibration data gets set, as one would expect. Then I've hex-dumped the calibration data, as well as the raw sensor data over several seconds worth of polling while leaving the JoyCons untouched on my desk.

Each JoyCon has a different small offset (on average) on their resting gyro output. And this offset, for each device, is approximately the same as the corresponding device's user gyro calibration numbers if they've been calibrated recently in the Switch system settings. Subtracting the user calibration data from the gyro data before using it results in much less drift.

I recommend trying it out yourself.

But the actionable item here is: your (excellent, really useful) tool should subtract the sensor_cal data from their corresponding gyro / accel before being used. Eg:
`jc->gyro.roll = (float)(uint16_to_int16(packet[19] | (packet[20] << 8) & 0xFF00) - jc->sensor_cal[1][0]) * ...conversion_to_SI;`

Thanks for your time!

**Comment by mfosse** [comment]
Thanks, I'll do this in the next update
